model = dict(
    type='AVAGFormer',
    neck=None,
    backbone=dict(
        type='pvt_v2_b5',
        init_weights_path='pretrained/pvt_v2_b5.pth'),
    vggish=dict(
        freeze_audio_extractor=True,
        pretrained_vggish_model_path='pretrained/vggish-10086976.pth',
        preprocess_audio_to_log_mel=False,
        postprocess_log_mel_with_pca=False,
        pretrained_pca_params_path=None),
    head=dict(
        type='AVSegHead',
        in_channels=[64, 128, 320, 512],
        num_classes=1,
        query_num=300,
        use_learnable_queries=True,
        fusion_block=dict(type='NewCrossModalMixer'),
        query_generator=dict(
            type='AttentionGenerator',
            num_layers=6,
            query_num=300),
        positional_encoding=dict(
            type='SinePositionalEncoding',
            num_feats=128),
        transformer=dict(
            type='AVSTransformer',
            encoder=dict(
                num_layers=6,
                layer=dict(
                    dim=256,
                    ffn_dim=2048,
                    dropout=0.1)),
            decoder=dict(
                num_layers=6,
                layer=dict(
                    dim=256,
                    ffn_dim=2048,
                    dropout=0.1)))),
    audio_dim=128,
    embed_dim=256,
    freeze_audio_backbone=True,
    T=20)
dataset = dict(
    train=dict(
        type='AVAffordanceDataset',
        split='train',
        anno_csv='./data/train.csv',
        dir_img='./data/',
        dir_audio_log_mel='./data/',
        dir_mask='./data/',
        img_size=(512, 512),
        mask_num=1,
        batch_size=24),
    val=dict(
        type='AVAffordanceDataset',
        split='val',
        anno_csv='./data/val.csv',
        dir_img='./data/',
        dir_audio_log_mel='./data/',
        dir_mask='./data/',
        img_size=(512, 512),
        mask_num=1,
        batch_size=24),
    test=dict(
        type='AVAffordanceDataset',
        split='test',
        anno_csv='./data/unseen.csv',
        dir_img='./data/',
        dir_audio_log_mel='./data/',
        dir_mask='./data',
        img_size=(512, 512),
        mask_num=1,
        batch_size=24))
optimizer = dict(
    type='AdamW',
    lr=2e-5)
loss = dict(
    weight_dict=dict(
        iou_loss_func=1.0,
        iou_loss_dep=1.0,
        mix_loss_func=0.1,
        mix_loss_dep=0.1
        ),
    loss_type='dice')
process = dict(
    num_works=32,
    train_epochs=25,
    warm_up_epochs = 5,
    freeze_epochs=10)
